//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lazyfitness.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class backManager
    {
        [Required(ErrorMessage ="必须填写用户名")]
        public int managerId { get; set; }
        [Required(ErrorMessage ="必须填写密码"), StringLength(maximumLength:50, MinimumLength =6, ErrorMessage ="密码必须大于6位")]
        public string managerPwd { get; set; }
    }
}
