//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lazyfitness.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class postArea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public postArea()
        {
            this.postInfo = new HashSet<postInfo>();
        }
    
        [Required(ErrorMessage="分区ID必须填写")]
        public int areaId { get; set; }
        [Required(ErrorMessage = "分区名称必须填写")]
        [StringLength(50)]
        public string areaName { get; set; }
        [Required(ErrorMessage = "分区描述必须填写")]
        public string areaBrief { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<postInfo> postInfo { get; set; }
    }
}
