//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lazyfitness.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class postReply
    {
        [Required(ErrorMessage = "论坛帖子ID是必填项！")]
        public int postId { get; set; }
        [Required(ErrorMessage = "评论者ID是必填项！")]
        public Nullable<int> userId { get; set; }
        public Nullable<System.DateTime> replyTime { get; set; }
        public string replyContent { get; set; }
    }
}
