//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lazyfitness.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class quesAnswInfo
    {
        [Required(ErrorMessage = "问答分区ID必须填写")]
        public int areaId { get; set; }
        [Required(ErrorMessage = "问答帖子ID必须填写")]
        public int quesAnswId { get; set; }
        [Required(ErrorMessage = "问答帖子标题必须填写")]
        [StringLength(50)]
        public string quesAnswTitle { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<System.DateTime> quesAnswTime { get; set; }
        public Nullable<int> pageView { get; set; }
        public Nullable<int> isPost { get; set; }
        public Nullable<int> quesAnswStatus { get; set; }
        public Nullable<int> amount { get; set; }
        [Required(ErrorMessage = "问答帖子描述必须填写")]
        [DataType(DataType.Text)]
        public string quesAnswContent { get; set; }
    
        public virtual quesArea quesArea { get; set; }
    }
}
