//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lazyfitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class resourceInfo
    {
        public int areaId { get; set; }
        public int resourceId { get; set; }
        public string resourceName { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<System.DateTime> resourceTime { get; set; }
        public Nullable<int> pageView { get; set; }
        public Nullable<int> isTop { get; set; }
        public string resourceContent { get; set; }
    }
}
