//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lazyfitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class serverShowInfo
    {
        public int id { get; set; }
        public Nullable<int> areaId { get; set; }
        public string title { get; set; }
        public string pictureAdr { get; set; }
        public string url { get; set; }
        public Nullable<int> flag { get; set; }
        public Nullable<int> Infostatus { get; set; }
    }
}
