//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lazyfitness.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;

    public partial class userSecurity
    {
        public int userId { get; set; }
        [Required(ErrorMessage ="必须填写登录名")]
        [StringLength(20,MinimumLength =3,ErrorMessage ="登录名长度必须大于3小于20")]
        public string loginId { get; set; }
        [Required(ErrorMessage = "必须填写密码")]
        [StringLength(40, MinimumLength = 3, ErrorMessage = "登录名长度必须大于3小于40")]
        public string userPwd { get; set; }
    
        public virtual userInfo userInfo { get; set; }
    }
}
