//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lazyfitness.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class userInfo
    {
        public int userId { get; set; }
        public string userName { get; set; }
        public Nullable<int> userAge { get; set; }
        public Nullable<int> userSex { get; set; }
        [StringLength(maximumLength:11, MinimumLength =11, ErrorMessage = "请填写正确的11位电话号码")]
        public string userTel { get; set; }
        public Nullable<int> userStatus { get; set; }
        public Nullable<int> userAccount { get; set; }
    
        public virtual userSecurity userSecurity { get; set; }
    }
}
